version: "3.8"

services:
  backend:
    restart: always
    container_name: "backend"
    image: backend
    build:
      context: ./backend
    environment:
      WORKERS: "4"
      PORT: "8000"
    ports:
      - "8000:8000"
    networks:
      - custom

  frontend:
    restart: always
    container_name: "frontend"
    image: frontend
    build:
      context: ./front
      args:
        REACT_APP_API_URL: http://127.0.0.1:8000/api
    ports:
      - "3000:80"
    networks:
      - custom

networks:
  custom:
    driver: bridge